apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: mug-frontend
  namespace: mug-{{ .Values.global.env }}
spec:  
  selector:
    matchLabels:
      app: mug-frontend
  template:
    metadata: 
      labels:
        app: mug-frontend
    spec: 
      containers: 
      - name: app
        image: {{ .Values.global.acr}}{{ .Values.image }}:{{ .Values.global.tag }}
        imagePullPolicy: Always
        env:
        - name: BASE_URL
          valueFrom:
            configMapKeyRef:
              name: environment-cm
              key: base.url
