apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: mug-backend
  namespace: mug
spec:  
  selector:
    matchLabels:
      app: mug-backend
  template:
    metadata: 
      labels:
        app: mug-backend
    spec: 
      containers: 
      - name: app
        image: mugacr.azurecr.io/mug-reservation-backend

