apiVersion: v1
kind: Secret
metadata:
  name: mug-storage-secret
  namespace: mug-dev
type: Opaque
data:
  azurestorageaccountname: bXVnc2FkYXRh
  azurestorageaccountkey: ZFhWL2VXUkNPc3Y4eURBOWErTG1YYzFlVXNML3lnUzUvRGtsZC9EeE9BVnhZcENlSnBtaWpoNVV4MUUwUWhrQUFqTHlrUlJLUjJTRUkwOGlHR3VkM3c9PQ==