apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: {{ .Values.name }}
  namespace: mug-{{ .Values.global.env }}
spec:  
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata: 
      labels:
        app: {{ .Values.name }}
    spec: 
      containers: 
      - name: app
        image: {{ .Values.global.acr }}{{ .Values.image }}
        env: 
        - name: MONGO_URL
          valueFrom:
            configMapKeyRef:
              name: environment-cm
              key: mongo.url
        {{ if .Values.busNeeded }}
        - name: BUS_CONNECTION_STRING
          valueFrom:
            configMapKeyRef:
              name: environment-cm
              key: bus.string
        {{ end }}



