{{ if .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
  namespace: mug-{{ .Values.global.env }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.service.port }}
{{ end }}