apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mug-ingress-front
  namespace: mug-{{ .Values.env }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: mug-controller # mug-{{ .Values.env }}-controller  TODO TERRAFORM
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: mug-frontend-service
          servicePort: 80

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mug-ingress-back
  namespace: mug-{{ .Values.env }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    kubernetes.io/ingress.class: mug-controller # mug-{{ .Values.env }}-controller  TODO TERRAFORM
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /back/?(.*)
        backend:
          serviceName: mug-backend-service
          servicePort: 80
      - path: /producer/?(.*)
        backend:
          serviceName: mug-producer-service
          servicePort: 80