apiVersion: apps/v1beta1
kind: Deployment
metadata:
 name: DEPLOYMENT_NAME 
 namespace: NAMESPACE
spec:
 template:
  metadata:
    labels:
      role: mongo
  spec:
    containers:
    - name: mongo
      image: mongo
      command:
        - mongod
        - "--bind_ip"  
        - 0.0.0.0     
      volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
      ports:
      - containerPort: 27017
    volumes:
    - name: mongo-storage
      emptyDir: {}
